ALTER TABLE communities
    ADD COLUMN ipeds_unitid CHAR(6) NULL,
    ADD COLUMN wikidata_id VARCHAR(32) NULL,
    ADD COLUMN ope_id VARCHAR(16) NULL,
    ADD COLUMN official_name VARCHAR(255) NULL,
    ADD COLUMN former_names JSON NULL,
    ADD COLUMN normalized_domain VARCHAR(253) NULL,
    ADD COLUMN address VARCHAR(255) NULL,
    ADD COLUMN city VARCHAR(100) NULL,
    ADD COLUMN state CHAR(2) NULL,
    ADD COLUMN zip VARCHAR(20) NULL,
    ADD COLUMN county VARCHAR(120) NULL,
    ADD COLUMN latitude DECIMAL(10,7) NULL,
    ADD COLUMN longitude DECIMAL(11,7) NULL,
    ADD COLUMN institution_sector VARCHAR(120) NULL,
    ADD COLUMN institution_level VARCHAR(80) NULL,
    ADD COLUMN institution_control VARCHAR(80) NULL,
    ADD COLUMN accreditor VARCHAR(255) NULL,
    ADD COLUMN degree_granting TINYINT(1) NULL,
    ADD COLUMN operating_status VARCHAR(80) NULL,
    ADD COLUMN is_hbcu TINYINT(1) NULL,
    ADD COLUMN is_tribal_college TINYINT(1) NULL,
    ADD COLUMN source_reporting_year SMALLINT UNSIGNED NULL,
    ADD COLUMN motto VARCHAR(500) NULL,
    ADD COLUMN slogan VARCHAR(255) NULL,
    ADD COLUMN nickname VARCHAR(255) NULL,
    ADD COLUMN logo_url VARCHAR(2048) NULL,
    ADD COLUMN logo_thumbnail_url VARCHAR(2048) NULL,
    ADD COLUMN logo_type VARCHAR(50) NULL,
    ADD COLUMN logo_mime_type VARCHAR(100) NULL,
    ADD COLUMN logo_license_name VARCHAR(255) NULL,
    ADD COLUMN logo_license_url VARCHAR(2048) NULL,
    ADD COLUMN logo_attribution TEXT NULL,
    ADD COLUMN logo_width INT UNSIGNED NULL,
    ADD COLUMN logo_height INT UNSIGNED NULL,
    ADD COLUMN first_seen_at DATETIME NULL,
    ADD COLUMN last_seen_at DATETIME NULL,
    ADD COLUMN last_directory_refresh_at DATETIME NULL,
    ADD COLUMN last_branding_refresh_at DATETIME NULL,
    ADD COLUMN last_logo_check_at DATETIME NULL,
    ADD COLUMN pipeline_active TINYINT(1) NULL,
    ADD COLUMN pipeline_review_required TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN pipeline_match_method VARCHAR(64) NULL,
    ADD COLUMN pipeline_match_confidence DECIMAL(5,4) NULL,
    ADD COLUMN pipeline_data_confidence DECIMAL(5,4) NULL,
    ADD COLUMN pipeline_last_error TEXT NULL,
    ADD COLUMN pipeline_last_error_at DATETIME NULL,
    ADD COLUMN pipeline_version VARCHAR(64) NULL,
    ADD COLUMN data_sources_json JSON NULL,
    ADD COLUMN data_confidence_json JSON NULL,
    ADD COLUMN data_verified_json JSON NULL,
    ADD COLUMN data_candidates_json JSON NULL,
    ADD COLUMN pipeline_metadata_json JSON NULL,
    ADD COLUMN manual_overrides_json JSON NULL,
    ALGORITHM=INSTANT;

ALTER TABLE communities
    ADD UNIQUE KEY uq_communities_ipeds_unitid (ipeds_unitid),
    ADD KEY idx_communities_ope_id (ope_id),
    ADD KEY idx_communities_wikidata_id (wikidata_id),
    ADD KEY idx_communities_normalized_domain (normalized_domain),
    ADD KEY idx_communities_pipeline_review (community_type, pipeline_review_required),
    ADD KEY idx_communities_pipeline_selection (community_type, pipeline_active, state),
    ALGORITHM=INPLACE,
    LOCK=NONE;
